name: Call parent script
description: Call a script in a parent directory
inputs:
  name:
    description: "Name"
    required: true
    default: "Jeff"
runs:
  using: composite
  steps:
    - name: Inspect directory
      shell: bash
      run: |
        ls -la
        pwd
        ls ../ -la
    - name: Call parent script
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: ../scripts/test.ps1 ${{ inputs.name }}
