name: Call parent script
description: Call a script in a parent directory
inputs:
  name:
    description: "Name"
    required: true
    default: "Jeff"
runs:
  using: composite
  steps:
    - name: Inspect directory
      shell: bash
      run: |
        ls -la
        pwd
        ls ../ -la
    - name: Call parent script
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: ../scripts/test.ps1 ${{ inputs.name }}
    - name: Test boolean output
      shell: pwsh
      id: test-output
      run: |
        Write-Output "assignment-needed=$true" >> $env:GITHUB_OUTPUT
    - name: Test conditional step
      if: steps.test-output.outputs.assignment-needed == 'true'
      shell: pwsh
      run: |
        Write-Output "Assignment not skipped!"
